services:
  postgres:
    image: postgres:15-alpine
    container_name: backend-postgres
    environment:
      POSTGRES_DB: cloudops_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
